import type { AmmoClass, DensityParams, DistanceMark, SightModel } from "./catalog.ts";

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

function round1(value: number): number {
  return Math.round(value * 10) / 10;
}

/**
 * Font defaults fitted from existing UserSights (excl. tanks generated by this app).
 * Stronger signal than zoomMax alone: zoomMin/zoomMax (fixed high-power optics
 * → larger text; wide zoom like Abrams 3–10× → smaller).
 */
function fontSizeFor(ammo: AmmoClass, zoomMin: number, zoomMax: number): number {
  const zMax = zoomMax > 0 ? zoomMax : 4;
  const zMin = zoomMin > 0 ? Math.min(zoomMin, zMax) : zMax;
  const ratio = zMin / zMax;

  if (ammo === "APDS") {
    // Higher baseline than raw corpus median: wide-zoom IFVs (Badger 2–8×)
    // were often hand-set ~0.7; pure ratio fit undershot them at ~0.4.
    return round1(clamp(0.28 * ratio + 0.63, 0.35, 1.15));
  }
  if (ammo === "HE") {
    return round1(clamp(0.5 * ratio + 0.45, 0.45, 1.15));
  }
  if (ammo === "HEAT") {
    return round1(clamp(0.38 * ratio + 0.37, 0.2, 1.1));
  }
  // AP and AP_Fast share the AP font curve.
  return round1(clamp(0.62 * ratio + 0.3, 0.35, 1.15));
}

/**
 * Layout/ticks: slow AP (≤800 m/s) → dense L/R @ 200 m;
 * AP_Fast → sparse left column; APDS/HEAT/HE as before.
 */
export function densityFor(
  zoomMax: number,
  ammo: AmmoClass,
  zoomMin: number = zoomMax,
): DensityParams {
  const zoom = zoomMax > 0 ? zoomMax : 4;
  const fontSizeMult = fontSizeFor(ammo, zoomMin, zoom);

  if (ammo === "APDS") {
    return {
      layout: "alternateLR",
      stepM: 400,
      minM: 400,
      maxM: 4000,
      numberEvery: 1,
      fontSizeMult,
      tickOuter: 2.1,
      tickInner: 0.9,
      circleSize: 1.8,
    };
  }

  if (ammo === "AP") {
    return {
      layout: "alternateLR",
      stepM: 200,
      minM: 200,
      maxM: zoom >= 8 ? 4000 : 3600,
      numberEvery: 1,
      fontSizeMult,
      tickOuter: 2.1,
      tickInner: 0.9,
      circleSize: 1.8,
    };
  }

  if (ammo === "HE") {
    return {
      layout: "singleLeft",
      stepM: 100,
      minM: 100,
      maxM: zoom >= 8 ? 2000 : 1600,
      numberEvery: 2,
      fontSizeMult,
      tickOuter: 4.8,
      tickInner: 1.5,
      circleSize: 2.5,
    };
  }

  const isHeat = ammo === "HEAT";
  // HEAT and AP_Fast: sparse left column (labels every 400 m).
  return {
    layout: "singleLeft",
    stepM: 200,
    minM: 200,
    maxM: zoom >= 8 ? 4000 : 3600,
    numberEvery: 2,
    fontSizeMult,
    tickOuter: isHeat ? 3.4 : 4.1,
    tickInner: isHeat ? 1.1 : 1.3,
    circleSize: isHeat ? 1.8 : 2.5,
  };
}

export function marksFromDensity(params: DensityParams): DistanceMark[] {
  const marks: DistanceMark[] = [];
  let index = 0;
  for (let meters = params.minM; meters <= params.maxM + 0.1; meters += params.stepM) {
    const showNumber =
      params.numberEvery === 1
        ? true
        : meters % (params.stepM * params.numberEvery) === 0;
    const label = showNumber ? Math.round(meters / 100) : 0;

    if (params.layout === "alternateLR") {
      const right = index % 2 === 1;
      marks.push({
        meters,
        label,
        // Tick only (p3.z). distancePos 0.005 pulls ticks left; -0.01 puts them
        // on the drop line. Same for L and R so left stubs are not leftover dots.
        sideOffset: -0.01,
        textPosX: right ? (index >= 3 ? 0.03 : 0.024) : 0,
      });
    } else {
      marks.push({
        meters,
        label,
        sideOffset: 0,
        textPosX: 0,
      });
    }
    index += 1;
  }
  return marks;
}

export function sightFromZoom(
  ammo: AmmoClass,
  zoomMax: number,
  overrides: Partial<Pick<SightModel, "fontSizeMult" | "tickOuter" | "tickInner">> = {},
  zoomMin: number = zoomMax,
): SightModel {
  const density = densityFor(zoomMax, ammo, zoomMin);
  return {
    ammo,
    fontSizeMult: overrides.fontSizeMult ?? density.fontSizeMult,
    lineSizeMult: 1,
    circleDiameter: 0.01,
    circleSize: density.circleSize,
    verticalLength: 400,
    tickOuter: overrides.tickOuter ?? density.tickOuter,
    tickInner: overrides.tickInner ?? density.tickInner,
    layout: density.layout,
    distancePosX: 0.005,
    marks: marksFromDensity(density),
  };
}

export { clamp };
